services:
  postgres:
    image: postgres:13
    container_name: postgres # Added for easier reference if needed
    ports:
      - "5432:5432"
    environment:
      # Read from .env, but these are primarily for the DB itself
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - ateda_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"] # Use env vars
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # MinIO Console
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      # Add other MinIO specific env vars if needed
    command: server /data --console-address ":9001"
    networks:
      - ateda_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]

  # Add Nessie Catalog Service
  nessie:
    image: ghcr.io/projectnessie/nessie:0.103.3-java
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      NESSIE_VERSION_STORE_TYPE: "JDBC2"
      NESSIE_VERSION_STORE_PERSIST_JDBC_DATASOURCE: "postgresql"
      QUARKUS_DATASOURCE_POSTGRESQL_JDBC_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
      QUARKUS_DATASOURCE_POSTGRESQL_USERNAME: "${POSTGRES_USER}"
      QUARKUS_DATASOURCE_POSTGRESQL_PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ateda_network

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...' &&
      until /usr/bin/mc config host add localminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do echo '...waiting...' && sleep 1; done &&
      echo 'MinIO host configured.' &&
      echo 'Attempting to create buckets: ${S3_LANDING_BUCKET}, ${S3_BRONZE_BUCKET}, ${S3_SILVER_BUCKET}, ${S3_GOLD_BUCKET}, ${DAGSTER_PIPES_BUCKET}' &&
      /usr/bin/mc mb --ignore-existing localminio/${S3_LANDING_BUCKET} &&
      /usr/bin/mc mb --ignore-existing localminio/${S3_BRONZE_BUCKET} &&
      /usr/bin/mc mb --ignore-existing localminio/${S3_SILVER_BUCKET} &&
      /usr/bin/mc mb --ignore-existing localminio/${S3_GOLD_BUCKET} &&
      /usr/bin/mc mb --ignore-existing localminio/${DAGSTER_PIPES_BUCKET} &&
      echo 'MinIO setup complete.'
      "
    environment:
      # These are needed by the mc commands
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      S3_LANDING_BUCKET: "${S3_LANDING_BUCKET}"
      S3_BRONZE_BUCKET: "${S3_BRONZE_BUCKET}"
      S3_SILVER_BUCKET: "${S3_SILVER_BUCKET}"
      S3_GOLD_BUCKET: "${S3_GOLD_BUCKET}"
      DAGSTER_PIPES_BUCKET: "${DAGSTER_PIPES_BUCKET}"
    networks:
      - ateda_network

volumes:
  postgres_data:
  minio_data:
  dagster_home: # Define volume for Dagster home

networks:
  ateda_network:
    driver: bridge
    name: ateda_network
