# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Map host port 9000 to NodePort 30000 (for Minio API Service)
  - containerPort: 30000
    hostPort: 9000
    protocol: TCP
  # Map host port 9001 to NodePort 30001 (for Minio Console Service)
  - containerPort: 30001
    hostPort: 9001
    protocol: TCP
  # Map host port 8030 to NodePort 30030 (for StarRocks FE Service)
  - containerPort: 30030
    hostPort: 8030
    protocol: TCP
  # Map host port 9030 to NodePort 30031 (for StarRocks FE Query Service)
  - containerPort: 30031
    hostPort: 9030
    protocol: TCP
  # Optional: Map host port 5432 to NodePort 30432 (for PostgreSQL Service)
  - containerPort: 30432
    hostPort: 5432
    protocol: TCP
  # Map host port 19120 to NodePort 30120 (for Nessie Service)
  - containerPort: 30120
    hostPort: 19120
    protocol: TCP