# infrastructure/k8s/secrets-dev.yaml
# This file should contain sensitive values for the dev environment.
# It is expected to be encrypted using helm-secrets (or similar) and
# decrypted by Helmfile during deployment.
# --- PLEASE REPLACE PLACEHOLDERS WITH ACTUAL VALUES ---

# Values injected into the component charts via {{ .Values... }}

# PostgreSQL Secrets (used by postgres and nessie charts)
postgres:
  username: "postgres"       # Replace with actual username
  password: "postgres"   # Replace with actual password

# Minio Secrets (used by minio chart)
minio:
  rootUser: "minioadmin"       # Replace with actual root user/access key
  rootPassword: "minioadmin" # Replace with actual root password/secret key 