[package]
name = "ateda-ingestor"
version = "0.1.0"
edition = "2024"

[dependencies]
apache-avro = { version = "0.18.0", features = ["snappy"] }
bytes = "1.5"
clap = { version = "4.5", features = ["derive", "env"] }
env_logger = "0.11"
futures = "0.3"
glob = "0.3"
log = "0.4"
num_cpus = "1.16"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
rayon = "1.10.0"
serde_json = "1.0.140"
tokio-stream = "0.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
uuid = { version = "1.16.0", features = ["v4"] }
walkdir = "2.5.0"
anyhow = "1.0"
minio-rsc = { version = "0.2.3", features = ["fs-tokio"] }
datafusion = { version = "47.0.0", features = ["avro"] }
hyper = { version = "1.6", features = ["full"] }
hyper-rustls = { version = "0.27", features = ["http1", "http2", "rustls-native-certs"] }
rustls = { version = "0.23"}
rustls-native-certs = "0.8"
url = "2.5.4"
dagster_pipes_rust = "0.1.8"


