apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-thrift-server.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-thrift-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "spark-thrift-server.fullname" . }}-role # Name of the Role created in role.yaml
subjects:
  - kind: ServiceAccount
    name: {{ include "spark-thrift-server.serviceAccountName" . }} # Name of the ServiceAccount created in serviceaccount.yaml
    namespace: {{ .Release.Namespace }} 